import os

script_dir = os.path.dirname(os.path.abspath(__file__))

SRC = os.path.join(script_dir, "test_source")
DST = os.path.join(script_dir, "test_destination")
SKIPPED = "skipped_files"

# Optional staging directory on a fast local drive.
# When set, all processing happens here first; at the end the result is
# bulk-copied to DST in one pass (much faster when DST is an external drive).
# Set to None to write directly to DST.
STAGING_DIR = "/tmp/ingest-staging"

# How to organize subdirectories:
#  - "id"     = group by ID segment
#  - "prefix" = group by characters 2–4 of first segment
#  - "auto"   = current behavior (id if present, otherwise prefix)
SUBDIR_MODE = "prefix"

# Personal overrides — generated by onboard.py, not tracked by git.
try:
    from user_config import *  # noqa: F401, F403
except ImportError:
    pass

# load resources
with open(
    os.path.join(script_dir, "resources", "ms-zustaendigkeit.txt"), encoding="utf-8"
) as f:
    valid_first_segment_first_char = [line.strip() for line in f if line.strip()]
with open(
    os.path.join(script_dir, "resources", "ms-kategorien.txt"), encoding="utf-8"
) as f:
    valid_first_segment_other_chars = [line.strip() for line in f if line.strip()]
with open(os.path.join(script_dir, "resources", "ms-id.txt"), encoding="utf-8") as f:
    valid_id_initial_chars = [line.strip() for line in f if line.strip()]
with open(
    os.path.join(script_dir, "resources", "ms-suffix.txt"), encoding="utf-8"
) as f:
    valid_suffixes = [line.strip() for line in f if line.strip()]
with open(
    os.path.join(script_dir, "resources", "ms-metadata-tags.txt"), encoding="utf-8"
) as f:
    required_metadata_tags = [
        line.strip() for line in f if line.strip() and not line.strip().startswith("#")
    ]
